name: Deploy FTP

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: deploy-ftp-master
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net
          username: if0_41595226
          password: Loi159357216132
          port: 21
          protocol: ftp
          server-dir: ./htdocs/
          dangerous-clean-slate: false
          exclude: |
            **/.git*/**
            **/.git*
            **/.venv/**
            **/__pycache__/**
            **/*.pyc
            **/.env
            **/eventos.db
            **/.DS_Store
            **/tests/**
